# Generated by Django 5.1.4 on 2025-01-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptedfile",
            name="file_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
