# Generated by Django 5.1.4 on 2025-01-15 18:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sharing", "0003_profle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profle",
            new_name="Profile",
        ),
    ]
